export const dummyJobs = [
  {
    companyId: "m0",
    responsibilities: "These are some responsibilities",
    createdAt: "7:55pm",
    country: null,
    state: "NY",
    city: "New York",
    isActive: true,
    recruiterId: null,
    zipcode: null,
    about: "You will have to do some work",
    qualifications: "Master's in Computer Science",
    updatedAt: "2024-04-28T23:56:27.780460+00:00",
    longitude: null,
    employmentType: null,
    locationType: null,
    minimumYearsOfExperience: null,
    skills: null,
    id: "1",
    latitude: null,
    title: "Software Engineer Intern",
  },
  {
    companyId: "company-id",
    responsibilities: "Some responsibilities",
    createdAt: "dummy time val",
    country: "USA",
    state: "MA",
    city: "Boston",
    isActive: true,
    recruiterId: "recruiter-id",
    zipcode: "11011",
    about: "Something about job",
    qualifications: "Some qualifications",
    updatedAt: "2024-05-01T00:51:30.470096+00:00",
    longitude: "-71.060511",
    employmentType: "Full-time",
    locationType: "Onsite",
    minimumYearsOfExperience: "3",
    skills: null,
    id: "test-job-id",
    latitude: "42.3554334",
    title: "Dummy Job",
  },
];
