import Image from "next/image";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const layout = ({ children }) => {
  return (
    <div className="flex flex-1">
      <div className="flex w-1/2 bg-blue-500 items-center justify-center">
        <Image
          priority
          src="/assets/swipply-logo.png"
          width={640}
          height={640}
          alt="Swipply logo"
        />
      </div>
      <div className="flex w-1/2 px-16 py-12">{children}</div>
    </div>
  );
};

export default layout;
