import { Inter } from "next/font/google";

import { persistor } from "@redux/store";
import ReduxProvider from "@redux/ReduxProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${inter.className} h-screen w-screen flex flex-col`}>
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
